### ISSUE TITLE
连续点击录音 停止 崩溃

### ISSUE THREAD

**Issue by qq171161636** [developerHaoz/SoundRecorderUtils#2]
Process: com.sid.soundrecorderutils, PID: 22352
    java.lang.RuntimeException: Unable to stop service com.sid.soundrecorderutils.RecordingService@4977446: java.lang.RuntimeException: stop failed.
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3852)
        at android.app.ActivityThread.access$1900(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: stop failed.
        at android.media.MediaRecorder.stop(Native Method)
        at com.sid.soundrecorderutils.RecordingService.stopRecording(RecordingService.java:98)
        at com.sid.soundrecorderutils.RecordingService.onDestroy(RecordingService.java:52)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3832)
        at android.app.ActivityThread.access$1900(ActivityThread.java:207) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by JanusKun** [comment]
处理了没？
